In [1]:
#Importando Pacotes:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#Importando MÃ³dulos:
#Importando Mais Limpeza de dados:
import clean_data as cd

In [2]:
gdp=pd.read_pickle('New/data.pickle').loc["GDP per capita (current US$)"][[str(num) for num in range(1975,2015)]]
cols = []
for i in range(1975,2015):
    cols.append(str(i))
gdp = gdp[cols].dropna()
gdp_chart=pd.DataFrame()
for i in gdp.index:
        x=pd.DataFrame({'Year':gdp.columns,'Country':[i]*len(gdp.columns),"GDP per capita (current US$)":gdp.T[i]})
        gdp_chart=pd.concat([gdp_chart,x])
gdp_chart=gdp_chart.fillna(0)
gdp_chart

      Year   Country  GDP per capita (current US$)
1975  1975   Algeria                    931.105517
1976  1976   Algeria                   1031.303135
1977  1977   Algeria                   1185.510635
1978  1978   Algeria                   1447.618021
1979  1979   Algeria                   1771.965549
1980  1980   Algeria                   2189.776680
1981  1981   Algeria                   2223.697344
1982  1982   Algeria                   2197.110500
1983  1983   Algeria                   2298.883805
1984  1984   Algeria                   2452.664632
1985  1985   Algeria                   2567.495905
1986  1986   Algeria                   2740.654724
1987  1987   Algeria                   2790.473919
1988  1988   Algeria                   2402.825627
1989  1989   Algeria                   2202.558090
1990  1990   Algeria                   2394.420380
1991  1991   Algeria                   1721.578696
1992  1992   Algeria                   1766.054678
1993  1993   Algeria                   1797.523561
1994  1994   Algeria                   1499.971505
1995  1995   Algeria                   1444.908036
1996  1996   Algeria                   1596.029867
1997  1997   Algeria                   1612.009303
1998  1998   Algeria                   1588.481449
1999  1999   Algeria                   1581.004564
2000  2000   Algeria                   1757.017797
2001  2001   Algeria                   1732.857979
2002  2002   Algeria                   1774.033673
2003  2003   Algeria                   2094.335506
2004  2004   Algeria                   2598.908023
...    ...       ...                           ...
1985  1985  Zimbabwe                    651.039658
1986  1986  Zimbabwe                    692.667302
1987  1987  Zimbabwe                    725.385754
1988  1988  Zimbabwe                    813.675382
1989  1989  Zimbabwe                    836.787602
1990  1990  Zimbabwe                    862.586588
1991  1991  Zimbabwe                    827.486940
1992  1992  Zimbabwe                    631.990604
1993  1993  Zimbabwe                    601.866877
1994  1994  Zimbabwe                    619.835138
1995  1995  Zimbabwe                    628.184925
1996  1996  Zimbabwe                    742.572673
1997  1997  Zimbabwe                    728.400836
1998  1998  Zimbabwe                    538.284856
1999  1999  Zimbabwe                    568.443953
2000  2000  Zimbabwe                    547.358878
2001  2001  Zimbabwe                    548.058731
2002  2002  Zimbabwe                    507.348003
2003  2003  Zimbabwe                    453.351155
2004  2004  Zimbabwe                    454.360665
2005  2005  Zimbabwe                    444.760508
2006  2006  Zimbabwe                    414.796232
2007  2007  Zimbabwe                    396.998217
2008  2008  Zimbabwe                    325.678570
2009  2009  Zimbabwe                    624.272242
2010  2010  Zimbabwe                    719.979516
2011  2011  Zimbabwe                    840.949877
2012  2012  Zimbabwe                    968.163875
2013  2013  Zimbabwe                   1026.388292
2014  2014  Zimbabwe                   1031.104614

[4800 rows x 3 columns]

In [3]:
Eletric_consuptiom = pd.read_pickle('New/data.pickle').loc['Electric power consumption (kWh per capita)'][[str(num) for num in range(1975,2015)]]
cols = []
for i in range(1975,2015):
    cols.append(str(i))
Eletric_consuptiom = Eletric_consuptiom[cols].dropna()
Eletric_consuptiom_chart=pd.DataFrame()
for i in Eletric_consuptiom.index:
        x=pd.DataFrame({'Year':Eletric_consuptiom.columns,'Country':[i]*len(Eletric_consuptiom.columns),'Electric power consumption (kWh per capita)':Eletric_consuptiom.T[i]})
        Eletric_consuptiom_chart=pd.concat([Eletric_consuptiom_chart,x])
Eletric_consuptiom_chart=Eletric_consuptiom_chart.fillna(0)
Eletric_consuptiom_chart

      Year   Country  Electric power consumption (kWh per capita)
1975  1975   Albania                                   739.345093
1976  1976   Albania                                   908.674547
1977  1977   Albania                                  1067.814156
1978  1978   Albania                                  1098.483166
1979  1979   Albania                                  1065.767398
1980  1980   Albania                                  1142.965355
1981  1981   Albania                                  1123.968106
1982  1982   Albania                                  1096.873229
1983  1983   Albania                                  1070.690164
1984  1984   Albania                                  1018.100288
1985  1985   Albania                                   796.353974
1986  1986   Albania                                  1420.614795
1987  1987   Albania                                  1161.951677
1988  1988   Albania                                  1005.939530
1989  1989   Albania                                  1021.393500
1990  1990   Albania                                   552.252185
1991  1991   Albania                                   418.453589
1992  1992   Albania                                   453.644074
1993  1993   Albania                                   536.363825
1994  1994   Albania                                   596.407959
1995  1995   Albania                                   663.783995
1996  1996   Albania                                   904.346640
1997  1997   Albania                                   694.664803
1998  1998   Albania                                   734.849914
1999  1999   Albania                                  1414.703784
2000  2000   Albania                                  1449.647413
2001  2001   Albania                                  1351.230796
2002  2002   Albania                                  1578.165919
2003  2003   Albania                                  1469.264539
2004  2004   Albania                                  1797.525487
...    ...       ...                                          ...
1985  1985  Zimbabwe                                   959.479987
1986  1986  Zimbabwe                                   893.361950
1987  1987  Zimbabwe                                   900.973316
1988  1988  Zimbabwe                                   880.022307
1989  1989  Zimbabwe                                   906.131154
1990  1990  Zimbabwe                                   886.565827
1991  1991  Zimbabwe                                   875.606851
1992  1992  Zimbabwe                                   803.248716
1993  1993  Zimbabwe                                   749.879238
1994  1994  Zimbabwe                                   787.716197
1995  1995  Zimbabwe                                   829.568284
1996  1996  Zimbabwe                                   869.054724
1997  1997  Zimbabwe                                   897.011331
1998  1998  Zimbabwe                                   865.531369
1999  1999  Zimbabwe                                   908.281851
2000  2000  Zimbabwe                                   872.834309
2001  2001  Zimbabwe                                   840.842735
2002  2002  Zimbabwe                                   839.964721
2003  2003  Zimbabwe                                   834.263569
2004  2004  Zimbabwe                                   805.008112
2005  2005  Zimbabwe                                   832.378158
2006  2006  Zimbabwe                                   807.587959
2007  2007  Zimbabwe                                   698.954509
2008  2008  Zimbabwe                                   573.294817
2009  2009  Zimbabwe                                   531.041412
2010  2010  Zimbabwe                                   546.842727
2011  2011  Zimbabwe                                   570.250932
2012  2012  Zimbabwe                                   542.729552
2013  2013  Zimbabwe                                   557.573925
2014  2014  Zimbabwe                                   536.995492

[4480 rows x 3 columns]

In [4]:
urban_population  = pd.read_pickle('New/data.pickle').loc['Urban population (% of total)'][[str(num) for num in range(1975,2015)]]
cols = []
for i in range(1975,2015):
    cols.append(str(i))
urban_population = urban_population[cols].dropna()
urban_population_chart=pd.DataFrame()
for i in urban_population.index:
        x=pd.DataFrame({'Year':urban_population.columns,'Country':[i]*len(urban_population.columns),'Urban population (% of total)':urban_population.T[i]})
        urban_population_chart=pd.concat([urban_population_chart,x])
urban_population_chart=urban_population_chart.fillna(0)
urban_population_chart

      Year      Country  Urban population (% of total)
1975  1975  Afghanistan                         13.641
1976  1976  Afghanistan                         14.074
1977  1977  Afghanistan                         14.517
1978  1978  Afghanistan                         14.973
1979  1979  Afghanistan                         15.442
1980  1980  Afghanistan                         15.995
1981  1981  Afghanistan                         16.562
1982  1982  Afghanistan                         17.147
1983  1983  Afghanistan                         17.747
1984  1984  Afghanistan                         18.365
1985  1985  Afghanistan                         18.997
1986  1986  Afghanistan                         19.647
1987  1987  Afghanistan                         20.314
1988  1988  Afghanistan                         20.998
1989  1989  Afghanistan                         21.088
1990  1990  Afghanistan                         21.177
1991  1991  Afghanistan                         21.266
1992  1992  Afghanistan                         21.355
1993  1993  Afghanistan                         21.444
1994  1994  Afghanistan                         21.534
1995  1995  Afghanistan                         21.624
1996  1996  Afghanistan                         21.714
1997  1997  Afghanistan                         21.805
1998  1998  Afghanistan                         21.895
1999  1999  Afghanistan                         21.986
2000  2000  Afghanistan                         22.078
2001  2001  Afghanistan                         22.169
2002  2002  Afghanistan                         22.261
2003  2003  Afghanistan                         22.353
2004  2004  Afghanistan                         22.500
...    ...          ...                            ...
1985  1985     Zimbabwe                         25.414
1986  1986     Zimbabwe                         26.105
1987  1987     Zimbabwe                         26.809
1988  1988     Zimbabwe                         27.524
1989  1989     Zimbabwe                         28.250
1990  1990     Zimbabwe                         28.988
1991  1991     Zimbabwe                         29.738
1992  1992     Zimbabwe                         30.499
1993  1993     Zimbabwe                         30.940
1994  1994     Zimbabwe                         31.335
1995  1995     Zimbabwe                         31.732
1996  1996     Zimbabwe                         32.132
1997  1997     Zimbabwe                         32.534
1998  1998     Zimbabwe                         32.939
1999  1999     Zimbabwe                         33.347
2000  2000     Zimbabwe                         33.758
2001  2001     Zimbabwe                         34.170
2002  2002     Zimbabwe                         34.585
2003  2003     Zimbabwe                         34.479
2004  2004     Zimbabwe                         34.294
2005  2005     Zimbabwe                         34.110
2006  2006     Zimbabwe                         33.926
2007  2007     Zimbabwe                         33.743
2008  2008     Zimbabwe                         33.560
2009  2009     Zimbabwe                         33.378
2010  2010     Zimbabwe                         33.196
2011  2011     Zimbabwe                         33.015
2012  2012     Zimbabwe                         32.834
2013  2013     Zimbabwe                         32.654
2014  2014     Zimbabwe                         32.504

[8520 rows x 3 columns]

In [5]:
merged=gdp_chart.merge(Eletric_consuptiom_chart)
merged=merged.merge(urban_population_chart)
merged=merged.drop(index=range(3280,3320))
merged

,Year,Country,GDP per capita (current US$),Electric power consumption (kWh per capita),Urban population (% of total)
0,1975,Algeria,931.105517,194.504802,40.330
1,1976,Algeria,1031.303135,218.728780,40.497
2,1977,Algeria,1185.510635,231.710422,40.928
3,1978,Algeria,1447.618021,277.284736,41.794
4,1979,Algeria,1771.965549,312.673884,42.665
5,1980,Algeria,2189.776680,328.322141,43.542
6,1981,Algeria,2223.697344,361.267619,44.420
7,1982,Algeria,2197.110500,403.631449,45.303
8,1983,Algeria,2298.883805,415.012251,46.189
9,1984,Algeria,2452.664632,438.661939,47.079
10,1985,Algeria,2567.495905,463.708413,47.968
11,1986,Algeria,2740.654724,482.374631,48.860
12,1987,Algeria,2790.473919,452.673577,49.722
13,1988,Algeria,2402.825627,478.986798,50.511
14,1989,Algeria,2202.558090,519.010620,51.298
15,1990,Algeria,2394.420380,528.434936,52.085
16,1991,Algeria,1721.578696,529.405205,52.871
17,1992,Algeria,1766.054678,556.636904,53.657
18,1993,Algeria,1797.523561,545.017593,54.439
19,1994,Algeria,1499.971505,548.087629,55.219
20,1995,Algeria,1444.908036,557.079781,55.997
21,1996,Algeria,1596.029867,567.704750,56.774
22,1997,Algeria,1612.009303,572.927769,57.544
23,1998,Algeria,1588.481449,615.577696,58.313
24,1999,Algeria,1581.004564,649.783900,59.118
25,2000,Algeria,1757.017797,680.195974,59.919
26,2001,Algeria,1732.857979,705.934793,60.712
27,2002,Algeria,1774.033673,727.612644,61.501
28,2003,Algeria,2094.335506,783.032359,62.284
29,2004,Algeria,2598.908023,800.704308,63.061
...,...,...,...,...,...
3370,1985,Zimbabwe,651.039658,959.479987,25.414
3371,1986,Zimbabwe,692.667302,893.361950,26.105
3372,1987,Zimbabwe,725.385754,900.973316,26.809
3373,1988,Zimbabwe,813.675382,880.022307,27.524
3374,1989,Zimbabwe,836.787602,906.131154,28.250
3375,1990,Zimbabwe,862.586588,886.565827,28.988
3376,1991,Zimbabwe,827.486940,875.606851,29.738
3377,1992,Zimbabwe,631.990604,803.248716,30.499
3378,1993,Zimbabwe,601.866877,749.879238,30.940
3379,1994,Zimbabwe,619.835138,787.716197,31.335
3380,1995,Zimbabwe,628.184925,829.568284,31.732
3381,1996,Zimbabwe,742.572673,869.054724,32.132
3382,1997,Zimbabwe,728.400836,897.011331,32.534
3383,1998,Zimbabwe,538.284856,865.531369,32.939
3384,1999,Zimbabwe,568.443953,908.281851,33.347
3385,2000,Zimbabwe,547.358878,872.834309,33.758
3386,2001,Zimbabwe,548.058731,840.842735,34.170
3387,2002,Zimbabwe,507.348003,839.964721,34.585
3388,2003,Zimbabwe,453.351155,834.263569,34.479
3389,2004,Zimbabwe,454.360665,805.008112,34.294
3390,2005,Zimbabwe,444.760508,832.378158,34.110
3391,2006,Zimbabwe,414.796232,807.587959,33.926
3392,2007,Zimbabwe,396.998217,698.954509,33.743
3393,2008,Zimbabwe,325.678570,573.294817,33.560
3394,2009,Zimbabwe,624.272242,531.041412,33.378
3395,2010,Zimbabwe,719.979516,546.842727,33.196
3396,2011,Zimbabwe,840.949877,570.250932,33.015
3397,2012,Zimbabwe,968.163875,542.729552,32.834
3398,2013,Zimbabwe,1026.388292,557.573925,32.654
3399,2014,Zimbabwe,1031.104614,536.995492,32.504

In [6]:
Continents={'Afghanistan': 'South Asia',
 'Albania': 'Europe & Central Asia',
 'Algeria': 'Middle East & North Africa',
 'American Samoa': 'East Asia & Pacific',
 'Andorra': 'Europe & Central Asia',
 'Angola': 'Sub-Saharan Africa',
 'Antigua and Barbuda': 'Latin America & Caribbean',
 'Argentina': 'Latin America & Caribbean',
 'Armenia': 'Europe & Central Asia',
 'Aruba': 'Latin America & Caribbean',
 'Australia': 'East Asia & Pacific',
 'Austria': 'Europe & Central Asia',
 'Azerbaijan': 'Europe & Central Asia',
 'Bahamas, The': 'Latin America & Caribbean',
 'Bahrain': 'Middle East & North Africa',
 'Bangladesh': 'South Asia',
 'Barbados': 'Latin America & Caribbean',
 'Belarus': 'Europe & Central Asia',
 'Belgium': 'Europe & Central Asia',
 'Belize': 'Latin America & Caribbean',
 'Benin': 'Sub-Saharan Africa',
 'Bermuda': 'North America',
 'Bhutan': 'South Asia',
 'Bolivia': 'Latin America & Caribbean',
 'Bosnia and Herzegovina': 'Europe & Central Asia',
 'Botswana': 'Sub-Saharan Africa',
 'Brazil': 'Latin America & Caribbean',
 'British Virgin Islands': 'Latin America & Caribbean',
 'Brunei Darussalam': 'East Asia & Pacific',
 'Bulgaria': 'Europe & Central Asia',
 'Burkina Faso': 'Sub-Saharan Africa',
 'Burundi': 'Sub-Saharan Africa',
 'Cabo Verde': 'Sub-Saharan Africa',
 'Cambodia': 'East Asia & Pacific',
 'Cameroon': 'Sub-Saharan Africa',
 'Canada': 'North America',
 'Cayman Islands': 'Latin America & Caribbean',
 'Central African Republic': 'Sub-Saharan Africa',
 'Chad': 'Sub-Saharan Africa',
 'Channel Islands': 'Europe & Central Asia',
 'Chile': 'Latin America & Caribbean',
 'China': 'East Asia & Pacific',
 'Colombia': 'Latin America & Caribbean',
 'Comoros': 'Sub-Saharan Africa',
 'Congo, Dem. Rep.': 'Sub-Saharan Africa',
 'Congo, Rep.': 'Sub-Saharan Africa',
 'Costa Rica': 'Latin America & Caribbean',
 'Croatia': 'Europe & Central Asia',
 'Cuba': 'Latin America & Caribbean',
 'CuraÃ§ao': 'Latin America & Caribbean',
 'Cyprus': 'Europe & Central Asia',
 'Czech Republic': 'Europe & Central Asia',
 "Cote d'Ivoire": 'Sub-Saharan Africa',
 'Denmark': 'Europe & Central Asia',
 'Djibouti': 'Middle East & North Africa',
 'Dominica': 'Latin America & Caribbean',
 'Dominican Republic': 'Latin America & Caribbean',
 'Ecuador': 'Latin America & Caribbean',
 'Egypt, Arab Rep.': 'Middle East & North Africa',
 'El Salvador': 'Latin America & Caribbean',
 'Equatorial Guinea': 'Sub-Saharan Africa',
 'Eritrea': 'Sub-Saharan Africa',
 'Estonia': 'Europe & Central Asia',
 'Eswatini': 'Sub-Saharan Africa',
 'Ethiopia': 'Sub-Saharan Africa',
 'Faroe Islands': 'Europe & Central Asia',
 'Fiji': 'East Asia & Pacific',
 'Finland': 'Europe & Central Asia',
 'France': 'Europe & Central Asia',
 'French Polynesia': 'East Asia & Pacific',
 'Gabon': 'Sub-Saharan Africa',
 'Gambia, The': 'Sub-Saharan Africa',
 'Georgia': 'Europe & Central Asia',
 'Germany': 'Europe & Central Asia',
 'Ghana': 'Sub-Saharan Africa',
 'Gibraltar': 'Europe & Central Asia',
 'Greece': 'Europe & Central Asia',
 'Greenland': 'Europe & Central Asia',
 'Grenada': 'Latin America & Caribbean',
 'Guam': 'East Asia & Pacific',
 'Guatemala': 'Latin America & Caribbean',
 'Guinea': 'Sub-Saharan Africa',
 'Guinea-Bissau': 'Sub-Saharan Africa',
 'Guyana': 'Latin America & Caribbean',
 'Haiti': 'Latin America & Caribbean',
 'Honduras': 'Latin America & Caribbean',
 'Hong Kong SAR, China': 'East Asia & Pacific',
 'Hungary': 'Europe & Central Asia',
 'Iceland': 'Europe & Central Asia',
 'India': 'South Asia',
 'Indonesia': 'East Asia & Pacific',
 'Iran, Islamic Rep.': 'Middle East & North Africa',
 'Iraq': 'Middle East & North Africa',
 'Ireland': 'Europe & Central Asia',
 'Isle of Man': 'Europe & Central Asia',
 'Israel': 'Middle East & North Africa',
 'Italy': 'Europe & Central Asia',
 'Jamaica': 'Latin America & Caribbean',
 'Japan': 'East Asia & Pacific',
 'Jordan': 'Middle East & North Africa',
 'Kazakhstan': 'Europe & Central Asia',
 'Kenya': 'Sub-Saharan Africa',
 'Kiribati': 'East Asia & Pacific',
 "Korea, Dem. People's Rep.": 'East Asia & Pacific',
 'Korea, Rep.': 'East Asia & Pacific',
 'Kosovo': 'Europe & Central Asia',
 'Kuwait': 'Middle East & North Africa',
 'Kyrgyz Republic': 'Europe & Central Asia',
 'Lao PDR': 'East Asia & Pacific',
 'Latvia': 'Europe & Central Asia',
 'Lebanon': 'Middle East & North Africa',
 'Lesotho': 'Sub-Saharan Africa',
 'Liberia': 'Sub-Saharan Africa',
 'Libya': 'Middle East & North Africa',
 'Liechtenstein': 'Europe & Central Asia',
 'Lithuania': 'Europe & Central Asia',
 'Luxembourg': 'Europe & Central Asia',
 'Macao SAR, China': 'East Asia & Pacific',
 'Macedonia, FYR': 'Europe & Central Asia',
 'Madagascar': 'Sub-Saharan Africa',
 'Malawi': 'Sub-Saharan Africa',
 'Malaysia': 'East Asia & Pacific',
 'Maldives': 'South Asia',
 'Mali': 'Sub-Saharan Africa',
 'Malta': 'Middle East & North Africa',
 'Marshall Islands': 'East Asia & Pacific',
 'Mauritania': 'Sub-Saharan Africa',
 'Mauritius': 'Sub-Saharan Africa',
 'Mexico': 'Latin America & Caribbean',
 'Micronesia, Fed. Sts.': 'East Asia & Pacific',
 'Moldova': 'Europe & Central Asia',
 'Monaco': 'Europe & Central Asia',
 'Mongolia': 'East Asia & Pacific',
 'Montenegro': 'Europe & Central Asia',
 'Morocco': 'Middle East & North Africa',
 'Mozambique': 'Sub-Saharan Africa',
 'Myanmar': 'East Asia & Pacific',
 'Namibia': 'Sub-Saharan Africa',
 'Nauru': 'East Asia & Pacific',
 'Nepal': 'South Asia',
 'Netherlands': 'Europe & Central Asia',
 'New Caledonia': 'East Asia & Pacific',
 'New Zealand': 'East Asia & Pacific',
 'Nicaragua': 'Latin America & Caribbean',
 'Niger': 'Sub-Saharan Africa',
 'Nigeria': 'Sub-Saharan Africa',
 'Northern Mariana Islands': 'East Asia & Pacific',
 'Norway': 'Europe & Central Asia',
 'Oman': 'Middle East & North Africa',
 'Pakistan': 'South Asia',
 'Palau': 'East Asia & Pacific',
 'Panama': 'Latin America & Caribbean',
 'Papua New Guinea': 'East Asia & Pacific',
 'Paraguay': 'Latin America & Caribbean',
 'Peru': 'Latin America & Caribbean',
 'Philippines': 'East Asia & Pacific',
 'Poland': 'Europe & Central Asia',
 'Portugal': 'Europe & Central Asia',
 'Puerto Rico': 'Latin America & Caribbean',
 'Qatar': 'Middle East & North Africa',
 'Romania': 'Europe & Central Asia',
 'Russian Federation': 'Europe & Central Asia',
 'Rwanda': 'Sub-Saharan Africa',
 'Samoa': 'East Asia & Pacific',
 'San Marino': 'Europe & Central Asia',
 'Saudi Arabia': 'Middle East & North Africa',
 'Senegal': 'Sub-Saharan Africa',
 'Serbia': 'Europe & Central Asia',
 'Seychelles': 'Sub-Saharan Africa',
 'Sierra Leone': 'Sub-Saharan Africa',
 'Singapore': 'East Asia & Pacific',
 'Sint Maarten (Dutch part)': 'Latin America & Caribbean',
 'Slovak Republic': 'Europe & Central Asia',
 'Slovenia': 'Europe & Central Asia',
 'Solomon Islands': 'East Asia & Pacific',
 'Somalia': 'Sub-Saharan Africa',
 'South Africa': 'Sub-Saharan Africa',
 'South Sudan': 'Sub-Saharan Africa',
 'Spain': 'Europe & Central Asia',
 'Sri Lanka': 'South Asia',
 'St. Kitts and Nevis': 'Latin America & Caribbean',
 'St. Lucia': 'Latin America & Caribbean',
 'St. Martin (French part)': 'Latin America & Caribbean',
 'St. Vincent and the Grenadines': 'Latin America & Caribbean',
 'Sudan': 'Sub-Saharan Africa',
 'Suriname': 'Latin America & Caribbean',
 'Sweden': 'Europe & Central Asia',
 'Switzerland': 'Europe & Central Asia',
 'Syrian Arab Republic': 'Middle East & North Africa',
 'SÃ£o TomÃ© and Principe': 'Sub-Saharan Africa',
 'Tajikistan': 'Europe & Central Asia',
 'Tanzania': 'Sub-Saharan Africa',
 'Thailand': 'East Asia & Pacific',
 'Timor-Leste': 'East Asia & Pacific',
 'Togo': 'Sub-Saharan Africa',
 'Tonga': 'East Asia & Pacific',
 'Trinidad and Tobago': 'Latin America & Caribbean',
 'Tunisia': 'Middle East & North Africa',
 'Turkey': 'Europe & Central Asia',
 'Turkmenistan': 'Europe & Central Asia',
 'Turks and Caicos Islands': 'Latin America & Caribbean',
 'Tuvalu': 'East Asia & Pacific',
 'Uganda': 'Sub-Saharan Africa',
 'Ukraine': 'Europe & Central Asia',
 'United Arab Emirates': 'Middle East & North Africa',
 'United Kingdom': 'Europe & Central Asia',
 'United States': 'North America',
 'Uruguay': 'Latin America & Caribbean',
 'Uzbekistan': 'Europe & Central Asia',
 'Vanuatu': 'East Asia & Pacific',
 'Venezuela, RB': 'Latin America & Caribbean',
 'Vietnam': 'East Asia & Pacific',
 'Virgin Islands (U.S.)': 'Latin America & Caribbean',
 'West Bank and Gaza': 'Middle East & North Africa',
 'Yemen, Rep.': 'Middle East & North Africa',
 'Zambia': 'Sub-Saharan Africa',
 'Zimbabwe': 'Sub-Saharan Africa'}

In [7]:
merged['Continents']=merged['Country'].apply(lambda x : Continents[x])
merged

,Year,Country,GDP per capita (current US$),Electric power consumption (kWh per capita),Urban population (% of total),Continents
0,1975,Algeria,931.105517,194.504802,40.330,Middle East & North Africa
1,1976,Algeria,1031.303135,218.728780,40.497,Middle East & North Africa
2,1977,Algeria,1185.510635,231.710422,40.928,Middle East & North Africa
3,1978,Algeria,1447.618021,277.284736,41.794,Middle East & North Africa
4,1979,Algeria,1771.965549,312.673884,42.665,Middle East & North Africa
5,1980,Algeria,2189.776680,328.322141,43.542,Middle East & North Africa
6,1981,Algeria,2223.697344,361.267619,44.420,Middle East & North Africa
7,1982,Algeria,2197.110500,403.631449,45.303,Middle East & North Africa
8,1983,Algeria,2298.883805,415.012251,46.189,Middle East & North Africa
9,1984,Algeria,2452.664632,438.661939,47.079,Middle East & North Africa
10,1985,Algeria,2567.495905,463.708413,47.968,Middle East & North Africa
11,1986,Algeria,2740.654724,482.374631,48.860,Middle East & North Africa
12,1987,Algeria,2790.473919,452.673577,49.722,Middle East & North Africa
13,1988,Algeria,2402.825627,478.986798,50.511,Middle East & North Africa
14,1989,Algeria,2202.558090,519.010620,51.298,Middle East & North Africa
15,1990,Algeria,2394.420380,528.434936,52.085,Middle East & North Africa
16,1991,Algeria,1721.578696,529.405205,52.871,Middle East & North Africa
17,1992,Algeria,1766.054678,556.636904,53.657,Middle East & North Africa
18,1993,Algeria,1797.523561,545.017593,54.439,Middle East & North Africa
19,1994,Algeria,1499.971505,548.087629,55.219,Middle East & North Africa
20,1995,Algeria,1444.908036,557.079781,55.997,Middle East & North Africa
21,1996,Algeria,1596.029867,567.704750,56.774,Middle East & North Africa
22,1997,Algeria,1612.009303,572.927769,57.544,Middle East & North Africa
23,1998,Algeria,1588.481449,615.577696,58.313,Middle East & North Africa
24,1999,Algeria,1581.004564,649.783900,59.118,Middle East & North Africa
25,2000,Algeria,1757.017797,680.195974,59.919,Middle East & North Africa
26,2001,Algeria,1732.857979,705.934793,60.712,Middle East & North Africa
27,2002,Algeria,1774.033673,727.612644,61.501,Middle East & North Africa
28,2003,Algeria,2094.335506,783.032359,62.284,Middle East & North Africa
29,2004,Algeria,2598.908023,800.704308,63.061,Middle East & North Africa
...,...,...,...,...,...,...
3370,1985,Zimbabwe,651.039658,959.479987,25.414,Sub-Saharan Africa
3371,1986,Zimbabwe,692.667302,893.361950,26.105,Sub-Saharan Africa
3372,1987,Zimbabwe,725.385754,900.973316,26.809,Sub-Saharan Africa
3373,1988,Zimbabwe,813.675382,880.022307,27.524,Sub-Saharan Africa
3374,1989,Zimbabwe,836.787602,906.131154,28.250,Sub-Saharan Africa
3375,1990,Zimbabwe,862.586588,886.565827,28.988,Sub-Saharan Africa
3376,1991,Zimbabwe,827.486940,875.606851,29.738,Sub-Saharan Africa
3377,1992,Zimbabwe,631.990604,803.248716,30.499,Sub-Saharan Africa
3378,1993,Zimbabwe,601.866877,749.879238,30.940,Sub-Saharan Africa
3379,1994,Zimbabwe,619.835138,787.716197,31.335,Sub-Saharan Africa
3380,1995,Zimbabwe,628.184925,829.568284,31.732,Sub-Saharan Africa
3381,1996,Zimbabwe,742.572673,869.054724,32.132,Sub-Saharan Africa
3382,1997,Zimbabwe,728.400836,897.011331,32.534,Sub-Saharan Africa
3383,1998,Zimbabwe,538.284856,865.531369,32.939,Sub-Saharan Africa
3384,1999,Zimbabwe,568.443953,908.281851,33.347,Sub-Saharan Africa
3385,2000,Zimbabwe,547.358878,872.834309,33.758,Sub-Saharan Africa
3386,2001,Zimbabwe,548.058731,840.842735,34.170,Sub-Saharan Africa
3387,2002,Zimbabwe,507.348003,839.964721,34.585,Sub-Saharan Africa
3388,2003,Zimbabwe,453.351155,834.263569,34.479,Sub-Saharan Africa
3389,2004,Zimbabwe,454.360665,805.008112,34.294,Sub-Saharan Africa
3390,2005,Zimbabwe,444.760508,832.378158,34.110,Sub-Saharan Africa
3391,2006,Zimbabwe,414.796232,807.587959,33.926,Sub-Saharan Africa
3392,2007,Zimbabwe,396.998217,698.954509,33.743,Sub-Saharan Africa
3393,2008,Zimbabwe,325.678570,573.294817,33.560,Sub-Saharan Africa
3394,2009,Zimbabwe,624.272242,531.041412,33.378,Sub-Saharan Africa
3395,2010,Zimbabwe,719.979516,546.842727,33.196,Sub-Saharan Africa
3396,2011,Zimbabwe,840.949877,570.250932,33.015,Sub-Saharan Africa
3397,2012,Zimbabwe,968.163875,542.729552,32.834,Sub-Saharan Africa
3398,2013,Zimbabwe,1026.388292,557.573925,32.654,Sub-Saharan Africa
3399,2014,Zimbabwe,1031.104614,536.995492,32.504,Sub-Saharan Africa

In [8]:
import plotly
plotly.tools.set_credentials_file(username='AngeloLJr', api_key='qDRwyLugi7YJQSBF6fl6')

In [9]:
import plotly.plotly as py
from plotly.grid_objs import Grid, Column
from plotly.tools import FigureFactory as FF 

import pandas as pd
import time

In [10]:
List_of_years = list(range(1975,2015))

List_Of_Continents = list(set(Continents.values()))

merged['Year']=merged['Year'].apply(int)

columns = []
# make grid
for year in List_of_years:
    for continent in List_Of_Continents:
        dataset_by_year = merged[merged['Year'] == int(year)]
        dataset_by_year_and_cont = dataset_by_year[dataset_by_year['Continents'] == continent]
        for col_name in dataset_by_year_and_cont:
            # each column name is unique
            column_name = '{year}_{continent}_{header}_gapminder_grid'.format(
                year=year, continent=continent, header=col_name
            )
            a_column = Column(list(dataset_by_year_and_cont[col_name]), column_name)
            columns.append(a_column)

# upload grid
grid = Grid(columns)
url = py.grid_ops.upload(grid, 'GDP.rateplot'+str(time.time()), auto_open=False)
url

'https://plot.ly/~AngeloLJr/105/'

In [11]:
figure1 = {
    'data': [],
    'layout': {},
    'frames': [],
    'config': {'scrollzoom': True}
}

# fill in most of layout
figure1['layout']['xaxis'] = {'title': 'Eletric Consuptiom per capita (Kw)', 'gridcolor': '#FFFFFF'}
figure1['layout']['yaxis'] = {'title': 'GDP per capita (current US$)', 'type': 'log', 'gridcolor': '#FFFFFF'}
figure1['layout']['hovermode'] = 'closest'
figure1['layout']['plot_bgcolor'] = 'rgb(223, 232, 243)'

In [12]:
sliders_dict = {
    'active': 0,
    'yanchor': 'top',
    'xanchor': 'left',
    'currentvalue': {
        'font': {'size': 20},
        'prefix': 'Year:',
        'visible': True,
        'xanchor': 'right'
    },
    'transition': {'duration': 300, 'easing': 'cubic-in-out'},
    'pad': {'b': 10, 't': 50},
    'len': 0.9,
    'x': 0.1,
    'y': 0,
    'steps': []
}

In [13]:
figure1['layout']['updatemenus'] = [
    {
        'buttons': [
            {
                'args': [None, {'frame': {'duration': 500, 'redraw': False},
                         'fromcurrent': True, 'transition': {'duration': 300, 'easing': 'quadratic-in-out'}}],
                'label': 'Play',
                'method': 'animate'
            },
            {
                'args': [[None], {'frame': {'duration': 0, 'redraw': False}, 'mode': 'immediate',
                'transition': {'duration': 0}}],
                'label': 'Pause',
                'method': 'animate'
            }
        ],
        'direction': 'left',
        'pad': {'r': 10, 't': 87},
        'showactive': False,
        'type': 'buttons',
        'x': 0.1,
        'xanchor': 'right',
        'y': 0,
        'yanchor': 'top'
    }
]

custom_colors = {
    'East Asia & Pacific': 'rgb(171, 99, 250)',
    'Europe & Central Asia': 'rgb(230, 99, 250)',
    'Africa': 'rgb(99, 110, 250)',
    'Latin America & Caribbean': 'rgb(25, 211, 243)',
    'Middle East & North Africa': 'rgb(50, 170, 255)',
    'North America':'rgb(215,20,20)',
    'South Asia':'rgb(20,215,20)',
    'Sub-Saharan Africa':'rgb(0,0,0)',
}

In [14]:
col_name_template = '{year}_{continent}_{header}_gapminder_grid'
year = 1975
for continent in List_Of_Continents:
    data_dict = {
        'xsrc': grid.get_column_reference(col_name_template.format(
            year=year, continent=continent, header='Electric power consumption (kWh per capita)'
        )),
        'ysrc': grid.get_column_reference(col_name_template.format(
            year=year, continent=continent, header='GDP per capita (current US$)'
        )),
        'mode': 'markers',
        'textsrc': grid.get_column_reference(col_name_template.format(
            year=year, continent=continent, header='Country'
        )),
        'marker': {
            'sizemode': 'area',
            'sizeref': 0.65,
            'sizesrc': grid.get_column_reference(col_name_template.format(
                 year=year, continent=continent, header='Urban population (% of total)'
            )),
            'color': custom_colors[continent]
        },
        'name': continent
    }
    figure1['data'].append(data_dict)

In [15]:
for year in List_of_years:
    frame = {'data': [], 'name': str(year)}
    for continent in List_Of_Continents:
        data_dict = {
            'xsrc': grid.get_column_reference(col_name_template.format(
                year=year, continent=continent, header='Electric power consumption (kWh per capita)'
            )),
            'ysrc': grid.get_column_reference(col_name_template.format(
                year=year, continent=continent, header='GDP per capita (current US$)'
            )),
            'mode': 'markers',
            'textsrc': grid.get_column_reference(col_name_template.format(
                year=year, continent=continent, header='Country'
            )),
            'marker': {
                'sizemode': 'area',
                'sizeref': 0.65,
                'sizesrc': grid.get_column_reference(col_name_template.format(
                     year=year, continent=continent, header='Urban population (% of total)'
                )),
                'color': custom_colors[continent]
         },
        'name': continent
        }
        frame['data'].append(data_dict)

    figure1['frames'].append(frame)
    slider_step = {'args': [
        [year],
        {'frame': {'duration': 300, 'redraw': False},
         'mode': 'immediate',
       'transition': {'duration': 300}}
     ],
     'label': year,
     'method': 'animate'}
    sliders_dict['steps'].append(slider_step)

figure1['layout']['sliders'] = [sliders_dict]

In [16]:
py.icreate_animations(figure1, 'Plot1CreditGDP'+str(time.time()))